---
- hosts: db
  become: 'yes'
  tasks:
    - name: 'Instalação de Pacotes BD'
      apt:
        pkg:
          - mariadb-server
          - wget
          - zip
          - curl
          - python3-mysqldb
        state: present
        update_cache: 'yes'
    - name: 'Criando DB Backup'
      mysql_db:
        name: backup
        state: present
        login_unix_socket: /run/mysqld/mysqld.sock
    - name: 'Download e extracao db'
      unarchive:
         src: https://github.com/rogerramossilva/devops/raw/master/db.zip
         dest: /tmp
         remote_src: yes
    - name: 'Importando script backup.sql'
      mysql_db:
         login_user: root
         login_password: ""
         state: import
         name: backup
         target: /tmp/backup.sql
    - name: 'Criacao do usuario Express no Mysql'
      mysql_user:
         host: '%'
         name: express
         password: 'AllSafe0!'
         priv: 'backup.*:ALL'
         state: present
         login_unix_socket: /run/mysqld/mysqld.sock
    - name: 'Subsituir Bind do mysql'
      replace:
         path: /etc/mysql/mariadb.conf.d/50-server.cnf
         regexp: '127\.0\.0\.1'
         replace: '0.0.0.0'
         notify: RestartMysql
  
  handlers:
    - name: RestartMysql
      service:
        name: mysql
        state: restarted
        enable: yes


